# Generated by Django 5.2.5 on 2025-08-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horse',
            options={'verbose_name': 'حصان', 'verbose_name_plural': 'الخيول'},
        ),
        migrations.AddField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='horses/photos/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='السلالة'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
    ]
