# Generated by Django 5.2.5 on 2025-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0002_alter_horse_options_horse_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم التواصل'),
        ),
        migrations.AddField(
            model_name='horse',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='horse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر (ريال)'),
        ),
        migrations.AddField(
            model_name='horse',
            name='specs',
            field=models.TextField(blank=True, null=True, verbose_name='المواصفات'),
        ),
    ]
