# Generated by Django 5.2.5 on 2025-08-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0003_horse_contact_phone_horse_location_horse_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الشريط')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'شريط أخبار',
                'verbose_name_plural': 'أشرطة الأخبار',
            },
        ),
    ]
